[package]
authors = ["Aphosis <alexy.long@orange.fr>"]
edition = "2018"
name = "palantir"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
walkdir = "2.3.1"

[dependencies]
gl = {path = "lib/gl"}
sdl2 = {version = "0.34.2", features = ["bundled", "static-link"]}
nalgebra = "0.21.1"

[features]
gl_debug = ["gl/debug"]
